<?php

use App\Enums\PermissionEnum;

Route::middleware(['auth', 'can:' . PermissionEnum::manage_orders()->value])
    ->prefix('orders')
    ->name('orders.')
    ->group(function () {
        Route::get(
            '/',
            \App\Http\Controllers\Order\IndexController::class
        )->name('index');
        Route::get(
            '/create',
            \App\Http\Controllers\Order\CreateController::class
        )->name('create');
        Route::post(
            '/',
            \App\Http\Controllers\Order\StoreController::class
        )->name('store');
        Route::get(
            '/{order}',
            \App\Http\Controllers\Order\ShowController::class
        )->name('show');
        Route::get(
            '/{order}/edit',
            \App\Http\Controllers\Order\EditController::class
        )->name('edit');
        Route::delete(
            '/{order}',
            \App\Http\Controllers\Order\DestroyController::class
        )->name('destroy');
        Route::get(
            '/{order}/general-information',
            \App\Http\Controllers\Order\GeneralInformation\EditController::class
        )->name('general-information.edit');
        Route::put(
            '/{order}/general-information',
            \App\Http\Controllers\Order\GeneralInformation\UpdateController::class
        )->name('general-information.update');
        Route::post(
            '/{order}/items',
            \App\Http\Controllers\Order\Item\StoreController::class
        )->name('items.store');
        Route::put(
            '/{order}/items/{orderItem}',
            \App\Http\Controllers\Order\Item\UpdateController::class
        )->name('items.update');
        Route::delete(
            '/{order}/items/{orderItem}',
            \App\Http\Controllers\Order\Item\DeleteController::class
        )->name('items.destroy');
        Route::put(
            '/{order}/items-discount',
            \App\Http\Controllers\Order\ItemsDiscount\UpdateController::class
        )->name('items-discount.update');
        Route::put(
            '/{order}/note',
            \App\Http\Controllers\Order\Note\UpdateController::class
        )->name('note.update');
        Route::put(
            '/{order}/contributors',
            \App\Http\Controllers\Order\Contributors\UpdateController::class
        )->name('contributors.update');
        Route::put(
            '/{order}/shipping',
            \App\Http\Controllers\Order\Shipping\UpdateController::class
        )->name('shipping.update');
        Route::put(
            '/{order}/payment',
            \App\Http\Controllers\Order\Payment\UpdateController::class
        )->name('payment.update');
        Route::put(
            '/{order}/status',
            \App\Http\Controllers\Order\Status\UpdateController::class
        )->name('status.update');
        Route::put(
            '/{order}/shipping-detail',
            \App\Http\Controllers\Order\ShippingDetail\UpdateController::class
        )->name('shipping-detail.update');
        Route::put(
            '/{order}/closing-date',
            \App\Http\Controllers\Order\ClosingDate\UpdateController::class
        )->name('closing-date.update');
    });
