<?php

Route::middleware(['auth'])
    ->prefix('return-order-items')
    ->name('return-order-items.')
    ->group(function () {
        Route::get(
            '/',
            \App\Http\Controllers\ReturnOrderItem\IndexController::class
        )->name('index');
        Route::get(
            '/create',
            \App\Http\Controllers\ReturnOrderItem\CreateController::class
        )->name('create');
        Route::post(
            '/',
            \App\Http\Controllers\ReturnOrderItem\StoreController::class
        )->name('store');
        Route::get(
            '/{returnOrderItem}',
            \App\Http\Controllers\ReturnOrderItem\EditController::class
        )->name('edit');
        Route::put(
            '/{returnOrderItem}',
            \App\Http\Controllers\ReturnOrderItem\UpdateController::class
        )->name('update');
        Route::delete(
            '/{returnOrderItem}',
            \App\Http\Controllers\ReturnOrderItem\DestroyController::class
        )->name('destroy');
    });
